// Copyright (c) 2024 DSR Corporation, Denver, Colorado.
// https://www.dsr-corporation.com
// SPDX-License-Identifier: Apache-2.0

use crate::{
    error, SDJWTFlattenedJson, SDJWTGeneralJson, SDJWTGeneralJsonSignature, SDJWTUnprotectedHeader,
};
use error::Result;
#[cfg(feature = "issuer-local")]
use std::collections::HashMap;
use std::collections::VecDeque;
use std::fmt;
use std::ops::Range;
use std::str::FromStr;
use std::vec::Vec;

use jsonwebtoken::jwk::{AlgorithmParameters, Jwk};
#[cfg(feature = "issuer-local")]
use jsonwebtoken::EncodingKey;
use jsonwebtoken::{Algorithm, Header};
use rand::{rngs::ThreadRng, Rng, RngCore};
#[cfg(feature = "issuer-local")]
use serde_json::Map as SJMap;
use serde_json::Value;
use serde_json::{json, Map};

#[cfg(feature = "issuer-local")]
use crate::disclosure::SDJWTDisclosure;
use crate::error::Error;
use crate::utils::{base64url_encode, generate_salt_with_rng};
use crate::{
    SDJWTCommon, SDJWTSerializationFormat, CNF_KEY, COMBINED_SERIALIZATION_FORMAT_SEPARATOR,
    DEFAULT_DIGEST_ALG, DEFAULT_SIGNING_ALG, DIGEST_ALG_KEY, JWK_KEY,
};

#[cfg(feature = "issuer-local")]
pub struct SDJWTIssuer {
    // parameters
    sign_alg: String,
    add_decoy_claims: bool,
    extra_header_parameters: Option<HashMap<String, String>>,

    // input data
    issuer_key: EncodingKey,
    holder_key: Option<Jwk>,

    // internal fields
    inner: SDJWTCommon,
    all_disclosures: Vec<SDJWTDisclosure>,
    sd_jwt_payload: SJMap<String, Value>,
    signed_sd_jwt: String,
    serialized_sd_jwt: String,
}

mod issuance_plan;

/// Deterministic fixtures for the opt-in Criterion issuance benchmark.
///
/// This module is unavailable unless the `issuance_bench` Cargo feature is
/// explicitly enabled. It is not part of the ordinary issuer API and cannot
/// change production executor selection.
#[cfg(feature = "issuance_bench")]
#[doc(hidden)]
pub mod issuance_benchmark;

use issuance_plan::IssuancePlan;

const DECOY_MIN_ELEMENTS: u32 = 2;
const DECOY_MAX_ELEMENTS: u32 = 5;
const PRIVATE_JWK_MEMBERS: [&str; 9] = ["d", "rsa_d", "p", "q", "dp", "dq", "qi", "oth", "k"];

fn validate_public_holder_key(holder_key: Option<&Jwk>) -> Result<()> {
    if holder_key.is_some_and(|key| matches!(key.algorithm, AlgorithmParameters::OctetKey(_))) {
        return Err(Error::InvalidInput(
            "holder_key must be a public asymmetric JWK".to_owned(),
        ));
    }
    Ok(())
}

fn validate_public_confirmation_claim(user_claims: &Value) -> Result<()> {
    let Some(jwk) = user_claims
        .get(CNF_KEY)
        .and_then(|confirmation| confirmation.get(JWK_KEY))
    else {
        return Ok(());
    };
    let object = jwk.as_object().ok_or_else(|| {
        Error::InvalidInput("cnf.jwk must be a public asymmetric JWK object".to_owned())
    })?;
    if object.get("kty").and_then(Value::as_str) == Some("oct")
        || PRIVATE_JWK_MEMBERS
            .iter()
            .any(|member| object.contains_key(*member))
    {
        return Err(Error::InvalidInput(
            "cnf.jwk must be a public asymmetric JWK".to_owned(),
        ));
    }
    Ok(())
}

/// ClaimsForSelectiveDisclosureStrategy is used to determine which claims can be selectively disclosed later by the holder.
#[derive(PartialEq, Debug)]
pub enum ClaimsForSelectiveDisclosureStrategy<'a> {
    /// No claims can be selectively disclosed, so all claims are always disclosed in presentations generated by the holder.
    NoSDClaims,
    /// Top-level claims can be selectively disclosed, nested objects are fully disclosed, if a parent claim is disclosed.
    TopLevel,
    /// All claims can be selectively disclosed (recursively including nested objects).
    AllLevels,
    /// Claims can be selectively disclosed based on the provided JSONPaths.
    /// Other claims are always disclosed in presentation generated by the holder.
    /// # Examples
    /// ```
    /// use sd_jwt_rs::issuer::ClaimsForSelectiveDisclosureStrategy;
    ///
    /// let strategy = ClaimsForSelectiveDisclosureStrategy::Custom(vec!["$.address", "$.address.street_address"]);
    /// ```
    Custom(Vec<&'a str>),
}

impl<'a> ClaimsForSelectiveDisclosureStrategy<'a> {
    fn finalize_input(&mut self) -> Result<()> {
        match self {
            ClaimsForSelectiveDisclosureStrategy::Custom(keys) => {
                for key in keys.iter_mut() {
                    if let Some(new_key) = key.strip_prefix("$.") {
                        *key = new_key;
                    } else {
                        return Err(Error::InvalidPath("Invalid JSONPath".to_owned()));
                    }
                }
                Ok(())
            }
            _ => Ok(()),
        }
    }

    fn next_level(&self, key: &str) -> Self {
        match self {
            Self::NoSDClaims => Self::NoSDClaims,
            Self::TopLevel => Self::NoSDClaims,
            Self::AllLevels => Self::AllLevels,
            Self::Custom(sd_keys) => {
                let next_sd_keys = sd_keys
                    .iter()
                    .filter_map(|str| {
                        str.strip_prefix(key)
                            .and_then(|str| match str.chars().next() {
                                Some('.') => Some(&str[1..]), // next token
                                Some('[') => Some(str),       // array index
                                _ => None,
                            })
                    })
                    .collect();
                Self::Custom(next_sd_keys)
            }
        }
    }

    fn sd_for_key(&self, key: &str) -> bool {
        match self {
            Self::NoSDClaims => false,
            Self::TopLevel => true,
            Self::AllLevels => true,
            Self::Custom(sd_keys) => sd_keys.contains(&key),
        }
    }
}

/// Issuer that prepares SD-JWT signing input without owning a signing key.
///
/// Call [`Self::prepare`], send [`PreparedSDJWT::signing_input`] to a remote
/// signer, then supply its raw signature bytes to [`PreparedSDJWT::complete`].
#[derive(Clone, Debug)]
pub struct SDJWTIssuerPlanner {
    sign_alg: String,
}

impl SDJWTIssuerPlanner {
    /// Create a remote-signing issuer planner.
    pub fn new(sign_alg: Option<String>) -> Self {
        Self {
            sign_alg: sign_alg.unwrap_or(DEFAULT_SIGNING_ALG.to_owned()),
        }
    }

    /// Prepare disclosures, the issuer payload, and the exact JWS signing input.
    pub fn prepare(
        &self,
        user_claims: Value,
        sd_strategy: ClaimsForSelectiveDisclosureStrategy<'_>,
        holder_key: Option<Jwk>,
        add_decoy_claims: bool,
        serialization_format: SDJWTSerializationFormat,
    ) -> Result<PreparedSDJWT> {
        #[cfg(all(feature = "mock_salts", test))]
        let _mock_salt_guard = crate::utils::seed_mock_salts_for_test();

        let mut random_source = LegacyIssuanceRandomSource::default();
        self.prepare_with_random_source(
            user_claims,
            sd_strategy,
            holder_key,
            add_decoy_claims,
            serialization_format,
            &mut random_source,
        )
    }

    fn prepare_with_random_source<R: IssuanceRandomSource>(
        &self,
        mut user_claims: Value,
        mut sd_strategy: ClaimsForSelectiveDisclosureStrategy<'_>,
        holder_key: Option<Jwk>,
        add_decoy_claims: bool,
        serialization_format: SDJWTSerializationFormat,
        random_source: &mut R,
    ) -> Result<PreparedSDJWT> {
        validate_public_holder_key(holder_key.as_ref())?;
        if holder_key.is_none() {
            validate_public_confirmation_claim(&user_claims)?;
        }
        sd_strategy.finalize_input()?;
        SDJWTCommon::check_for_sd_claim(&user_claims)?;

        let claims_obj_ref = user_claims
            .as_object_mut()
            .ok_or(Error::ConversionError("json object".to_string()))?;
        if holder_key.is_some() {
            claims_obj_ref.shift_remove(CNF_KEY);
        }
        let mut always_revealed_claims: Map<String, Value> = ["iss", "iat", "exp"]
            .into_iter()
            .filter_map(|key| claims_obj_ref.shift_remove_entry(key))
            .collect();

        let assembly =
            IssuancePlan::create(user_claims, sd_strategy, add_decoy_claims, random_source)?
                .execute()?;
        let disclosures = assembly
            .disclosures
            .into_iter()
            .map(|disclosure| disclosure.raw_b64)
            .collect();
        let mut payload = assembly
            .claims
            .as_object()
            .ok_or(Error::ConversionError("json object".to_string()))?
            .clone();
        payload.insert(
            DIGEST_ALG_KEY.to_owned(),
            Value::String(DEFAULT_DIGEST_ALG.to_owned()),
        );
        payload.append(&mut always_revealed_claims);
        if let Some(holder_key) = holder_key {
            payload.insert(CNF_KEY.to_owned(), json!({JWK_KEY: holder_key}));
        }

        let algorithm = Algorithm::from_str(&self.sign_alg)
            .map_err(|error| Error::DeserializationError(error.to_string()))?;
        let mut header = Header::new(algorithm);
        // Preserve the legacy issuer's current protected header exactly.
        header.typ = None;
        let protected = base64url_encode(
            &serde_json::to_vec(&header)
                .map_err(|error| Error::DeserializationError(error.to_string()))?,
        );
        let payload = base64url_encode(
            &serde_json::to_vec(&payload)
                .map_err(|error| Error::DeserializationError(error.to_string()))?,
        );
        let signing_input = format!("{protected}.{payload}");

        Ok(PreparedSDJWT {
            algorithm,
            disclosures,
            payload,
            protected,
            serialization_format,
            signing_input,
        })
    }
}

#[cfg(test)]
mod public_holder_key_tests {
    use super::*;

    #[derive(Default)]
    struct CountingRandomSource {
        calls: usize,
    }

    impl IssuanceRandomSource for CountingRandomSource {
        fn disclosure_salt(&mut self) -> String {
            self.calls += 1;
            "salt".to_owned()
        }

        fn decoy_count(&mut self, _range: Range<u32>) -> u32 {
            self.calls += 1;
            2
        }

        fn decoy_salt(&mut self) -> String {
            self.calls += 1;
            "decoy".to_owned()
        }
    }

    #[test]
    fn planner_rejects_symmetric_holder_key_before_randomness() {
        let holder_key: Jwk = serde_json::from_value(json!({
            "kty": "oct",
            "k": "c3VwZXItc2VjcmV0"
        }))
        .expect("valid symmetric JWK fixture");
        let mut random_source = CountingRandomSource::default();

        let error = SDJWTIssuerPlanner::new(None)
            .prepare_with_random_source(
                json!({"given_name":"Alice"}),
                ClaimsForSelectiveDisclosureStrategy::AllLevels,
                Some(holder_key),
                true,
                SDJWTSerializationFormat::Compact,
                &mut random_source,
            )
            .expect_err("symmetric holder key must be rejected");

        assert!(matches!(error, Error::InvalidInput(_)));
        assert_eq!(random_source.calls, 0);
    }

    #[test]
    fn planner_rejects_private_raw_confirmation_before_randomness() {
        for member in PRIVATE_JWK_MEMBERS {
            let mut jwk = json!({"kty":"EC","crv":"P-256","x":"x","y":"y"});
            jwk.as_object_mut()
                .unwrap()
                .insert(member.to_owned(), json!("secret"));
            let mut random_source = CountingRandomSource::default();
            let error = SDJWTIssuerPlanner::new(None)
                .prepare_with_random_source(
                    json!({"given_name":"Alice","cnf":{"jwk":jwk}}),
                    ClaimsForSelectiveDisclosureStrategy::AllLevels,
                    None,
                    true,
                    SDJWTSerializationFormat::Compact,
                    &mut random_source,
                )
                .expect_err("private cnf.jwk must be rejected");
            assert!(matches!(error, Error::InvalidInput(_)));
            assert_eq!(random_source.calls, 0, "randomness consumed for {member}");
        }
    }
}

/// Prepared SD-JWT state awaiting one remote signature.
#[derive(Clone)]
pub struct PreparedSDJWT {
    algorithm: Algorithm,
    disclosures: Vec<String>,
    payload: String,
    protected: String,
    serialization_format: SDJWTSerializationFormat,
    signing_input: String,
}

impl fmt::Debug for PreparedSDJWT {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("PreparedSDJWT")
            .field("algorithm", &self.algorithm)
            .field("disclosure_count", &self.disclosures.len())
            .field("contents", &"[redacted]")
            .finish()
    }
}

impl PreparedSDJWT {
    /// Algorithm the remote signer must use.
    pub fn algorithm(&self) -> Algorithm {
        self.algorithm
    }

    /// Exact ASCII JWS signing input (`base64url(header).base64url(payload)`).
    pub fn signing_input(&self) -> &[u8] {
        self.signing_input.as_bytes()
    }

    /// Assemble the requested SD-JWT serialization from raw signature bytes.
    pub fn complete(self, signature: &[u8]) -> Result<String> {
        validate_remote_signature(self.algorithm, signature)?;
        self.complete_encoded_signature(base64url_encode(signature))
    }

    fn complete_encoded_signature(self, signature: String) -> Result<String> {
        let signed_sd_jwt = format!("{}.{}", self.signing_input, signature);
        match self.serialization_format {
            SDJWTSerializationFormat::Compact => {
                let mut parts = VecDeque::with_capacity(self.disclosures.len() + 1);
                parts.push_back(signed_sd_jwt);
                parts.extend(self.disclosures);
                Ok(format!(
                    "{}{}",
                    parts
                        .iter()
                        .map(String::as_str)
                        .collect::<Vec<_>>()
                        .join(COMBINED_SERIALIZATION_FORMAT_SEPARATOR),
                    COMBINED_SERIALIZATION_FORMAT_SEPARATOR,
                ))
            }
            SDJWTSerializationFormat::FlattenedJson => serde_json::to_string(&SDJWTFlattenedJson {
                protected: self.protected,
                payload: self.payload,
                signature,
                header: SDJWTUnprotectedHeader {
                    disclosures: self.disclosures,
                    kb_jwt: None,
                },
            })
            .map_err(|error| Error::DeserializationError(error.to_string())),
            SDJWTSerializationFormat::GeneralJson => serde_json::to_string(&SDJWTGeneralJson {
                payload: self.payload,
                signatures: vec![SDJWTGeneralJsonSignature {
                    protected: self.protected,
                    signature,
                    header: SDJWTUnprotectedHeader {
                        disclosures: self.disclosures,
                        kb_jwt: None,
                    },
                }],
            })
            .map_err(|error| Error::DeserializationError(error.to_string())),
        }
    }
}

fn validate_remote_signature(algorithm: Algorithm, signature: &[u8]) -> Result<()> {
    let valid = match algorithm {
        Algorithm::ES256 => p256::ecdsa::Signature::from_slice(signature).is_ok(),
        Algorithm::ES384 => p384::ecdsa::Signature::from_slice(signature).is_ok(),
        Algorithm::EdDSA => validate_ed25519_encoding(signature),
        Algorithm::RS256
        | Algorithm::RS384
        | Algorithm::RS512
        | Algorithm::PS256
        | Algorithm::PS384
        | Algorithm::PS512 => signature.len() >= 256 && signature.iter().any(|byte| *byte != 0),
        _ => {
            return Err(Error::InvalidInput(format!(
                "unsupported remote signing algorithm: {algorithm:?}"
            )))
        }
    };
    if !valid {
        return Err(Error::InvalidInput(format!(
            "invalid {algorithm:?} remote signature encoding: got {} bytes",
            signature.len()
        )));
    }
    Ok(())
}

fn validate_ed25519_encoding(signature: &[u8]) -> bool {
    let Ok(bytes) = <&[u8; 64]>::try_from(signature) else {
        return false;
    };
    let (encoded_r, encoded_s) = bytes.split_at(32);
    let Ok(encoded_r) = <[u8; 32]>::try_from(encoded_r) else {
        return false;
    };
    let Ok(encoded_s) = <[u8; 32]>::try_from(encoded_s) else {
        return false;
    };
    let Some(point) = curve25519_dalek::edwards::CompressedEdwardsY(encoded_r).decompress() else {
        return false;
    };
    point.compress().to_bytes() == encoded_r
        && !point.is_small_order()
        && bool::from(curve25519_dalek::scalar::Scalar::from_canonical_bytes(encoded_s).is_some())
        && signature.iter().any(|byte| *byte != 0)
}

trait IssuanceRandomSource {
    fn disclosure_salt(&mut self) -> String;
    fn decoy_count(&mut self, range: Range<u32>) -> u32;
    fn decoy_salt(&mut self) -> String;
}

struct LegacyIssuanceRandomSource<R> {
    rng: Option<R>,
    initialize: fn() -> R,
}

#[cfg(feature = "issuer-local")]
struct IssuanceOptions {
    holder_key: Option<Jwk>,
    add_decoy_claims: bool,
    serialization_format: SDJWTSerializationFormat,
}

impl Default for LegacyIssuanceRandomSource<ThreadRng> {
    fn default() -> Self {
        Self {
            rng: None,
            initialize: rand::thread_rng,
        }
    }
}

impl<R> LegacyIssuanceRandomSource<R> {
    fn rng(&mut self) -> &mut R {
        self.rng.get_or_insert_with(self.initialize)
    }
}

impl<R> IssuanceRandomSource for LegacyIssuanceRandomSource<R>
where
    R: RngCore,
{
    fn disclosure_salt(&mut self) -> String {
        #[cfg(not(feature = "mock_salts"))]
        {
            generate_salt_with_rng(self.rng())
        }
        #[cfg(feature = "mock_salts")]
        {
            crate::utils::generate_salt_mock()
        }
    }

    fn decoy_count(&mut self, range: Range<u32>) -> u32 {
        self.rng().gen_range(range)
    }

    fn decoy_salt(&mut self) -> String {
        generate_salt_with_rng(self.rng())
    }
}

#[cfg(feature = "issuer-local")]
impl SDJWTIssuer {
    /// Creates a new SDJWTIssuer instance.
    ///
    /// The instance can be used mutliple times to issue SD-JWTs.
    ///
    /// # Arguments
    /// * `issuer_key` - The key used to sign the SD-JWT.
    /// * `sign_alg` - The signing algorithm used to sign the SD-JWT. If not provided, the default algorithm is used.
    ///
    /// # Returns
    /// A new SDJWTIssuer instance.
    pub fn new(issuer_key: EncodingKey, sign_alg: Option<String>) -> Self {
        SDJWTIssuer {
            sign_alg: sign_alg.unwrap_or(DEFAULT_SIGNING_ALG.to_owned()),
            add_decoy_claims: false,
            extra_header_parameters: None,
            issuer_key,
            holder_key: None,
            inner: Default::default(),
            all_disclosures: vec![],
            sd_jwt_payload: Default::default(),
            signed_sd_jwt: "".to_string(),
            serialized_sd_jwt: "".to_string(),
        }
    }

    fn reset(&mut self) {
        self.extra_header_parameters = Default::default();
        self.all_disclosures = Default::default();
        self.sd_jwt_payload = Default::default();
        self.signed_sd_jwt = Default::default();
        self.serialized_sd_jwt = Default::default();
    }

    /// Issues a SD-JWT.
    ///
    /// # Arguments
    /// * `user_claims` - The claims to be included in the SD-JWT. A top-level
    ///   `cnf` claim is preserved when `holder_key` is not provided and replaced
    ///   when it is provided.
    /// * `sd_strategy` - The strategy to be used to determine which claims to be selectively disclosed. See [ClaimsForSelectiveDisclosureStrategy] for more details.
    /// * `holder_key` - The Holder public JWK included in the top-level `cnf`
    ///   claim for key binding. When provided, it takes precedence over a
    ///   top-level `cnf` value in `user_claims`.
    /// * `add_decoy_claims` - If true, decoy claims are added to the SD-JWT.
    /// * `serialization_format` - The serialization format to be used for the SD-JWT, see [SDJWTSerializationFormat].
    ///
    /// # Returns
    /// The issued SD-JWT as a string in the requested serialization format.
    pub fn issue_sd_jwt(
        &mut self,
        user_claims: Value,
        sd_strategy: ClaimsForSelectiveDisclosureStrategy,
        holder_key: Option<Jwk>,
        add_decoy_claims: bool,
        serialization_format: SDJWTSerializationFormat,
        // extra_header_parameters: Option<HashMap<String, String>>,
    ) -> Result<String> {
        #[cfg(all(feature = "mock_salts", test))]
        let _mock_salt_guard = crate::utils::seed_mock_salts_for_test();

        let mut random_source = LegacyIssuanceRandomSource::default();
        self.issue_sd_jwt_with_random_source(
            user_claims,
            sd_strategy,
            holder_key,
            add_decoy_claims,
            serialization_format,
            &mut random_source,
        )
    }

    fn issue_sd_jwt_with_random_source<R: IssuanceRandomSource>(
        &mut self,
        user_claims: Value,
        sd_strategy: ClaimsForSelectiveDisclosureStrategy,
        holder_key: Option<Jwk>,
        add_decoy_claims: bool,
        serialization_format: SDJWTSerializationFormat,
        random_source: &mut R,
    ) -> Result<String> {
        self.issue_sd_jwt_with_plan_executor(
            user_claims,
            sd_strategy,
            IssuanceOptions {
                holder_key,
                add_decoy_claims,
                serialization_format,
            },
            random_source,
            IssuancePlan::execute,
        )
    }

    fn issue_sd_jwt_with_plan_executor<R, F>(
        &mut self,
        user_claims: Value,
        mut sd_strategy: ClaimsForSelectiveDisclosureStrategy,
        options: IssuanceOptions,
        random_source: &mut R,
        execute_plan: F,
    ) -> Result<String>
    where
        R: IssuanceRandomSource,
        F: FnOnce(IssuancePlan) -> Result<issuance_plan::IssuanceAssembly>,
    {
        validate_public_holder_key(options.holder_key.as_ref())?;
        if options.holder_key.is_none() {
            validate_public_confirmation_claim(&user_claims)?;
        }
        let inner = SDJWTCommon {
            serialization_format: options.serialization_format,
            ..Default::default()
        };

        sd_strategy.finalize_input()?;

        SDJWTCommon::check_for_sd_claim(&user_claims)?;

        self.reset();
        self.inner = inner;
        self.holder_key = options.holder_key;
        self.add_decoy_claims = options.add_decoy_claims;

        self.assemble_sd_jwt_payload(user_claims, sd_strategy, random_source, execute_plan)?;
        self.create_signed_jws()?;
        self.create_combined()?;

        Ok(self.serialized_sd_jwt.clone())
    }

    fn assemble_sd_jwt_payload<R, F>(
        &mut self,
        mut user_claims: Value,
        sd_strategy: ClaimsForSelectiveDisclosureStrategy,
        random_source: &mut R,
        execute_plan: F,
    ) -> Result<()>
    where
        R: IssuanceRandomSource,
        F: FnOnce(IssuancePlan) -> Result<issuance_plan::IssuanceAssembly>,
    {
        let claims_obj_ref = user_claims
            .as_object_mut()
            .ok_or(Error::ConversionError("json object".to_string()))?;
        if self.holder_key.is_some() {
            claims_obj_ref.shift_remove(CNF_KEY);
        }
        let always_revealed_root_keys = vec!["iss", "iat", "exp"];
        let mut always_revealed_claims: Map<String, Value> = always_revealed_root_keys
            .into_iter()
            .filter_map(|key| claims_obj_ref.shift_remove_entry(key))
            .collect();

        let plan = IssuancePlan::create(
            user_claims,
            sd_strategy,
            self.add_decoy_claims,
            random_source,
        )?;
        let assembly = execute_plan(plan)?;
        self.all_disclosures = assembly.disclosures;
        self.sd_jwt_payload = assembly
            .claims
            .as_object()
            .ok_or(Error::ConversionError("json object".to_string()))?
            .clone();

        self.sd_jwt_payload.insert(
            DIGEST_ALG_KEY.to_owned(),
            Value::String(DEFAULT_DIGEST_ALG.to_owned()),
        ); //TODO
        self.sd_jwt_payload.append(&mut always_revealed_claims);

        if let Some(holder_key) = &self.holder_key {
            self.sd_jwt_payload
                .insert(CNF_KEY.to_owned(), json!({JWK_KEY: holder_key}));
        }

        Ok(())
    }

    fn create_signed_jws(&mut self) -> Result<()> {
        if let Some(extra_headers) = &self.extra_header_parameters {
            let mut _protected_headers = extra_headers.clone();
            for (key, value) in extra_headers.iter() {
                _protected_headers.insert(key.to_string(), value.to_string());
            }
            unimplemented!("extra_headers are not supported for issuance");
        }

        let mut header = Header::new(
            Algorithm::from_str(&self.sign_alg)
                .map_err(|e| Error::DeserializationError(e.to_string()))?,
        );
        header.typ = self.inner.typ.clone();
        self.signed_sd_jwt = jsonwebtoken::encode(&header, &self.sd_jwt_payload, &self.issuer_key)
            .map_err(|e| Error::DeserializationError(e.to_string()))?;

        Ok(())
    }

    fn create_combined(&mut self) -> Result<()> {
        match self.inner.serialization_format {
            SDJWTSerializationFormat::Compact => {
                let mut disclosures: VecDeque<String> = self
                    .all_disclosures
                    .iter()
                    .map(|d| d.raw_b64.to_string())
                    .collect();
                disclosures.push_front(self.signed_sd_jwt.clone());

                let disclosures: Vec<&str> = disclosures.iter().map(|s| s.as_str()).collect();

                self.serialized_sd_jwt = format!(
                    "{}{}",
                    disclosures.join(COMBINED_SERIALIZATION_FORMAT_SEPARATOR),
                    COMBINED_SERIALIZATION_FORMAT_SEPARATOR,
                );
            }
            SDJWTSerializationFormat::FlattenedJson => {
                let (protected, payload, signature) = SDJWTCommon::split_jwt(&self.signed_sd_jwt)?;
                let header = SDJWTUnprotectedHeader {
                    kb_jwt: None,
                    disclosures: self
                        .all_disclosures
                        .iter()
                        .map(|d| d.raw_b64.to_string())
                        .collect(),
                };
                let flattened_json = SDJWTFlattenedJson {
                    protected,
                    payload,
                    signature,
                    header,
                };
                self.serialized_sd_jwt = serde_json::to_string(&flattened_json)
                    .map_err(|e| Error::DeserializationError(e.to_string()))?;
            }
            SDJWTSerializationFormat::GeneralJson => {
                let (protected, payload, signature) = SDJWTCommon::split_jwt(&self.signed_sd_jwt)?;
                let header = SDJWTUnprotectedHeader {
                    kb_jwt: None,
                    disclosures: self
                        .all_disclosures
                        .iter()
                        .map(|d| d.raw_b64.to_string())
                        .collect(),
                };
                let general_json = SDJWTGeneralJson {
                    payload,
                    signatures: vec![SDJWTGeneralJsonSignature {
                        protected,
                        signature,
                        header,
                    }],
                };
                self.serialized_sd_jwt = serde_json::to_string(&general_json)
                    .map_err(|e| Error::DeserializationError(e.to_string()))?;
            }
        }

        Ok(())
    }
}

#[cfg(all(test, feature = "issuer-local"))]
mod tests {
    use jsonwebtoken::{Algorithm, EncodingKey};
    use log::trace;
    use serde_json::json;

    use crate::issuer::{validate_remote_signature, ClaimsForSelectiveDisclosureStrategy};
    use crate::{SDJWTIssuer, SDJWTIssuerPlanner, SDJWTSerializationFormat};

    const PRIVATE_ISSUER_PEM: &str = "-----BEGIN PRIVATE KEY-----\nMIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgUr2bNKuBPOrAaxsR\nnbSH6hIhmNTxSGXshDSUD1a1y7ihRANCAARvbx3gzBkyPDz7TQIbjF+ef1IsxUwz\nX1KWpmlVv+421F7+c1sLqGk4HUuoVeN8iOoAcE547pJhUEJyf5Asc6pP\n-----END PRIVATE KEY-----\n";

    #[test]
    fn test_assembly_sd_full_recursive() {
        let user_claims = json!({
            "sub": "6c5c0a49-b589-431d-bae7-219122a9ec2c",
            "iss": "https://example.com/issuer",
            "iat": 1683000000,
            "exp": 1883000000,
            "address": {
                "street_address": "Schulstr. 12",
                "locality": "Schulpforta",
                "region": "Sachsen-Anhalt",
                "country": "DE"
            }
        });
        let private_issuer_bytes = PRIVATE_ISSUER_PEM.as_bytes();
        let issuer_key = EncodingKey::from_ec_pem(private_issuer_bytes).unwrap();
        let sd_jwt = SDJWTIssuer::new(issuer_key, None)
            .issue_sd_jwt(
                user_claims,
                ClaimsForSelectiveDisclosureStrategy::AllLevels,
                None,
                false,
                SDJWTSerializationFormat::Compact,
            )
            .unwrap();
        trace!("{sd_jwt:?}")
    }

    #[test]
    fn remote_planner_preserves_all_local_serializations() {
        let claims = json!({
            "sub": "6c5c0a49-b589-431d-bae7-219122a9ec2c",
            "iss": "https://example.com/issuer",
            "iat": 1683000000,
            "exp": 1883000000,
            "given_name": "Erika"
        });
        let issuer_key = EncodingKey::from_ec_pem(PRIVATE_ISSUER_PEM.as_bytes()).unwrap();

        for serialization_format in [
            SDJWTSerializationFormat::Compact,
            SDJWTSerializationFormat::FlattenedJson,
            SDJWTSerializationFormat::GeneralJson,
        ] {
            let prepared = SDJWTIssuerPlanner::new(None)
                .prepare(
                    claims.clone(),
                    ClaimsForSelectiveDisclosureStrategy::NoSDClaims,
                    None,
                    false,
                    serialization_format.clone(),
                )
                .unwrap();
            let encoded_signature = jsonwebtoken::crypto::sign(
                prepared.signing_input(),
                &issuer_key,
                prepared.algorithm(),
            )
            .unwrap();
            let signature = crate::utils::base64url_decode(&encoded_signature).unwrap();
            let remote = prepared.complete(&signature).unwrap();

            let local = SDJWTIssuer::new(issuer_key.clone(), None)
                .issue_sd_jwt(
                    claims.clone(),
                    ClaimsForSelectiveDisclosureStrategy::NoSDClaims,
                    None,
                    false,
                    serialization_format,
                )
                .unwrap();

            assert_eq!(remote, local);
        }
    }

    #[test]
    fn remote_planner_rejects_malformed_es256_signatures() {
        let prepare = || {
            SDJWTIssuerPlanner::new(Some("ES256".to_string()))
                .prepare(
                    json!({"sub": "example"}),
                    ClaimsForSelectiveDisclosureStrategy::NoSDClaims,
                    None,
                    false,
                    SDJWTSerializationFormat::Compact,
                )
                .unwrap()
        };

        assert!(prepare().complete(&[]).is_err());
        assert!(prepare().complete(&[0u8; 63]).is_err());

        let mut der_encoded = vec![0u8; 70];
        der_encoded[0] = 0x30;
        assert!(prepare().complete(&der_encoded).is_err());

        assert!(prepare().complete(&[0u8; 64]).is_err());
        assert!(prepare().complete(&[0xffu8; 64]).is_err());

        let mut valid = [0u8; 64];
        valid[31] = 1;
        valid[63] = 1;
        assert!(prepare().complete(&valid).is_ok());
    }

    #[test]
    fn remote_signature_validation_covers_supported_algorithms() {
        let mut es384 = [0u8; 96];
        es384[47] = 1;
        es384[95] = 1;
        assert!(validate_remote_signature(Algorithm::ES384, &es384).is_ok());
        assert!(validate_remote_signature(Algorithm::ES384, &[0u8; 96]).is_err());

        let mut eddsa = [0u8; 64];
        eddsa[..32].copy_from_slice(
            curve25519_dalek::constants::ED25519_BASEPOINT_POINT
                .compress()
                .as_bytes(),
        );
        eddsa[32] = 1;
        assert!(validate_remote_signature(Algorithm::EdDSA, &eddsa).is_ok());
        assert!(validate_remote_signature(Algorithm::EdDSA, &[0u8; 64]).is_err());
        let mut bad_s = eddsa;
        bad_s[63] = 0xff;
        assert!(validate_remote_signature(Algorithm::EdDSA, &bad_s).is_err());

        for algorithm in [
            Algorithm::RS256,
            Algorithm::RS384,
            Algorithm::RS512,
            Algorithm::PS256,
            Algorithm::PS384,
            Algorithm::PS512,
        ] {
            assert!(validate_remote_signature(algorithm, &[1u8; 256]).is_ok());
            assert!(validate_remote_signature(algorithm, &[1u8; 384]).is_ok());
            assert!(validate_remote_signature(algorithm, &[0u8; 256]).is_err());
            assert!(validate_remote_signature(algorithm, &[1u8; 255]).is_err());
        }
        assert!(validate_remote_signature(Algorithm::HS256, &[1u8; 256]).is_err());
    }

    #[test]
    fn test_next_level_array() {
        let strategy = ClaimsForSelectiveDisclosureStrategy::Custom(vec![
            "name",
            "addresses[1]",
            "addresses[1].country",
            "nationalities[0]",
        ]);

        let next_strategy = strategy.next_level("addresses");
        assert_eq!(
            &next_strategy,
            &ClaimsForSelectiveDisclosureStrategy::Custom(vec!["[1]", "[1].country"])
        );
        let next_strategy = next_strategy.next_level("[1]");
        assert_eq!(
            &next_strategy,
            &ClaimsForSelectiveDisclosureStrategy::Custom(vec!["country"])
        );
    }

    #[test]
    fn test_next_level_object() {
        let strategy = ClaimsForSelectiveDisclosureStrategy::Custom(vec![
            "address.street_address",
            "address.locality",
            "address.region",
            "address.country",
        ]);

        let next_strategy = strategy.next_level("address");
        assert_eq!(
            &next_strategy,
            &ClaimsForSelectiveDisclosureStrategy::Custom(vec![
                "street_address",
                "locality",
                "region",
                "country"
            ])
        );
    }
}

#[cfg(all(test, feature = "issuer-planning"))]
mod issuer_planning_tests {
    use jsonwebtoken::Algorithm;
    use serde_json::json;

    use super::{validate_remote_signature, ClaimsForSelectiveDisclosureStrategy};
    use crate::{SDJWTIssuerPlanner, SDJWTSerializationFormat};

    #[test]
    fn remote_planner_rejects_malformed_es256_signatures() {
        let prepare = || {
            SDJWTIssuerPlanner::new(Some("ES256".to_string()))
                .prepare(
                    json!({"sub": "example"}),
                    ClaimsForSelectiveDisclosureStrategy::NoSDClaims,
                    None,
                    false,
                    SDJWTSerializationFormat::Compact,
                )
                .unwrap()
        };

        assert!(prepare().complete(&[]).is_err());
        assert!(prepare().complete(&[0u8; 63]).is_err());
        let mut der_encoded = vec![0u8; 70];
        der_encoded[0] = 0x30;
        assert!(prepare().complete(&der_encoded).is_err());
        assert!(prepare().complete(&[0u8; 64]).is_err());
        assert!(prepare().complete(&[0xffu8; 64]).is_err());

        let mut valid = [0u8; 64];
        valid[31] = 1;
        valid[63] = 1;
        assert!(prepare().complete(&valid).is_ok());
    }

    #[test]
    fn remote_signature_validation_covers_supported_algorithms() {
        let mut es384 = [0u8; 96];
        es384[47] = 1;
        es384[95] = 1;
        assert!(validate_remote_signature(Algorithm::ES384, &es384).is_ok());
        assert!(validate_remote_signature(Algorithm::ES384, &[0u8; 96]).is_err());

        let mut eddsa = [0u8; 64];
        eddsa[..32].copy_from_slice(
            curve25519_dalek::constants::ED25519_BASEPOINT_POINT
                .compress()
                .as_bytes(),
        );
        eddsa[32] = 1;
        assert!(validate_remote_signature(Algorithm::EdDSA, &eddsa).is_ok());
        assert!(validate_remote_signature(Algorithm::EdDSA, &[0u8; 64]).is_err());
        let mut bad_s = eddsa;
        bad_s[63] = 0xff;
        assert!(validate_remote_signature(Algorithm::EdDSA, &bad_s).is_err());

        for algorithm in [
            Algorithm::RS256,
            Algorithm::RS384,
            Algorithm::RS512,
            Algorithm::PS256,
            Algorithm::PS384,
            Algorithm::PS512,
        ] {
            assert!(validate_remote_signature(algorithm, &[1u8; 256]).is_ok());
            assert!(validate_remote_signature(algorithm, &[1u8; 384]).is_ok());
            assert!(validate_remote_signature(algorithm, &[0u8; 256]).is_err());
            assert!(validate_remote_signature(algorithm, &[1u8; 255]).is_err());
        }
        assert!(validate_remote_signature(Algorithm::HS256, &[1u8; 256]).is_err());
    }
}

#[cfg(all(test, feature = "issuer-local"))]
mod issuance_contract_tests;
